# Generated by Django 2.2.16 on 2022-03-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_cat_gen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
