# Generated by Django 2.2.16 on 2022-03-25 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220325_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Error invalid username', regex='^[\\w.@+-]+\\z')]),
        ),
    ]
