# Generated by Django 2.2.16 on 2022-03-25 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220325_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Error invalid slug', regex='^[\\w.@+-]+\\z')]),
        ),
    ]
