# Generated by Django 2.2.16 on 2022-03-25 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220325_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Error invalid username', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
