# Generated by Django 2.2.16 on 2022-03-20 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(-2000000), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
