# Generated by Django 2.2.16 on 2022-03-20 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20220320_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='raiting',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
