# Generated by Django 2.2.16 on 2022-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
