# Generated by Django 2.2.16 on 2022-03-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_title_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='raiting',
            field=models.IntegerField(default=None),
        ),
    ]
