# Generated by Django 2.2.16 on 2022-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='titles.Genre'),
        ),
    ]
